import { useEffect, useState, type CSSProperties } from "react";
import * as api from "./api";
import { Empty, Layout, Loader, MealCard, MealPhoto, Notice, PageHeader, Stat, Stepper } from "./components";
import { Link, navigate, usePath } from "./router";
import type { Account, Activity, Dashboard, Favorite, Inventory, Meal, Profile, Progress, Recovery, Workout } from "./types";

const profileDefaults: Omit<Profile, "id"> = { age: 30, sex: "prefer_not_to_say", height_cm: 170, weight_kg: 70, fitness_goal: "maintain_weight", foods_to_avoid: [], favorite_foods: [], max_prep_minutes: 20, unit_preference: "metric" };
const accountDefaults: Account = { display_name: "Athlete", email: null, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", avatar_url: null };
const activities: Activity[] = ["walking", "hiking", "running", "cycling", "unknown"];
const friendly = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, (char: string) => char.toUpperCase());
const errorText = (error: unknown) => error instanceof Error ? error.message : "Something went wrong.";
const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)) : "Recently";

function HomePage() {
  const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState("");
  useEffect(() => { api.getDashboard().then(setData).catch(e => setError(errorText(e))); }, []);
  if (!data && !error) return <Loader label="Preparing your dashboard" />;
  if (!data) return <><PageHeader title="Welcome to Recovery Meal" subtitle="Set up your profile to start building better recovery habits." /><Empty title="Let's get you set up" body={error} action={<Link className="button primary" to="/profile">Create profile</Link>} /></>;
  const workout = data.latest_workout; const meal = data.latest_meal;
  return <>
    <PageHeader title={`Good ${new Date().getHours() < 12 ? "morning" : new Date().getHours() < 18 ? "afternoon" : "evening"}, ${data.account.display_name.split(" ")[0]}! 👋`} subtitle="Fuel your recovery. Build strength. Feel your best." action={<Link to="/get-meal" className="button primary large">♨ Get today's recovery meal</Link>} />
    <div className="home-grid">
      <section className="panel workout-card"><div className="section-title"><span>◉</span><b>Latest workout</b></div>{workout ? <><h2>{friendly(workout.activity_type)}</h2><p className="muted">{formatDate(workout.started_at)}</p><div className="stats-grid"><Stat icon="♨" label="Energy" value={workout.estimated_calories ? `${workout.estimated_calories.low}–${workout.estimated_calories.high} kcal` : "—"} /><Stat icon="◷" label="Duration" value={`${Math.round((workout.duration_seconds || 0) / 60)} min`} /><Stat icon="♡" label="Avg heart rate" value={workout.avg_heart_rate ? `${Math.round(workout.avg_heart_rate)} bpm` : "—"} /></div><Notice type="success">✓ Great work! Your body is ready to refuel.</Notice></> : <Empty title="No workout yet" body="Upload a GPX workout to get a tailored meal." action={<Link className="button primary" to="/get-meal">Upload workout</Link>} />}</section>
      <section className="panel latest-meal"><div className="section-title"><span>♨</span><b>Your latest recovery meal</b></div>{meal ? <div className="latest-meal-inner"><MealPhoto meal={meal} /><div><h2>{meal.name}</h2><p className="muted">{meal.selected_at ? formatDate(meal.selected_at) : "Selected"}</p><p>{meal.estimated_calories} kcal &nbsp;·&nbsp; {meal.protein_g}g protein &nbsp;·&nbsp; {meal.prep_minutes} min</p><p className="muted clamp">{meal.rationale}</p><Link to={`/meals/${meal.id}`} className="text-link">View meal details →</Link></div></div> : <Empty title="No meal logged" body="Your selected recovery meal will appear here." action={<Link className="button primary" to="/get-meal">Get a meal</Link>} />}</section>
      <section className="panel consistency"><div className="section-title"><span>▥</span><b>Your recovery consistency</b><small>This week</small></div><div className="consistency-score"><div><strong>{data.week.selected}</strong> of {data.week.goal}<span>recovery meals logged</span></div><div className="ring" style={{ "--percent": `${data.week.percent * 3.6}deg` } as CSSProperties}><b>{data.week.percent}%</b></div></div><WeekDots days={data.week.days} /><Notice type="success">♧ You're building a strong habit. Keep it up!</Notice></section>
      <section className="panel recent"><div className="section-title"><span>◷</span><b>Recent activity</b></div>{data.recent_activity.length ? <div className="activity-list">{data.recent_activity.map((item, i) => <div key={`${item.at}-${i}`}><span>{item.type === "meal" ? "♨" : item.type === "favorite" ? "♡" : "◉"}</span><div><b>{item.title}</b><small>{item.detail}</small></div><time>{formatDate(item.at)}</time></div>)}</div> : <p className="muted">Your recent activity will show here.</p>}<Link to="/progress" className="text-link">View all activity →</Link></section>
    </div>
    <div className="tip-banner"><span>♧</span><div><b>Recovery tip</b><small>Refuel within 2 hours after your workout to support muscle repair and performance.</small></div></div>
  </>;
}

function WeekDots({ days }: { days: { date: string; selected: boolean; today: boolean }[] }) { return <div className="week-dots">{days.map(day => <div key={day.date}><small>{new Date(`${day.date}T12:00:00`).toLocaleDateString(undefined, { weekday: "short" }).slice(0, 2)}</small><span className={day.selected ? "selected" : day.today ? "today" : ""}>{day.selected ? "✓" : ""}</span></div>)}</div>; }

function ProfilePage() {
  const [form, setForm] = useState(profileDefaults); const [account, setAccount] = useState(accountDefaults); const [height, setHeight] = useState("170"); const [weight, setWeight] = useState("70"); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { Promise.allSettled([api.getProfile(), api.getAccount()]).then(([p, a]) => { if (p.status === "fulfilled") { setForm(p.value); setHeight(String(p.value.unit_preference === "imperial" ? Math.round(p.value.height_cm / 2.54 * 10) / 10 : p.value.height_cm)); setWeight(String(p.value.unit_preference === "imperial" ? Math.round(p.value.weight_kg * 2.20462 * 10) / 10 : p.value.weight_kg)); } if (a.status === "fulfilled") setAccount(a.value); setLoading(false); }); }, []);
  const update = <K extends keyof typeof form>(key: K, value: (typeof form)[K]) => setForm(current => ({ ...current, [key]: value }));
  const save = async () => { try { setError(""); const saved = await api.saveProfile({ ...form, height_cm: form.unit_preference === "imperial" ? Number(height) * 2.54 : Number(height), weight_kg: form.unit_preference === "imperial" ? Number(weight) / 2.20462 : Number(weight) }); setForm(saved); const savedAccount = await api.saveAccount({ display_name: account.display_name, email: account.email, timezone: account.timezone }); setAccount(savedAccount); setMessage("Your profile is up to date."); } catch (e) { setError(errorText(e)); } };
  const switchUnits = (unit: "metric" | "imperial") => { if (unit === form.unit_preference) return; const cm = form.unit_preference === "imperial" ? Number(height) * 2.54 : Number(height); const kg = form.unit_preference === "imperial" ? Number(weight) / 2.20462 : Number(weight); setHeight(String(Math.round((unit === "imperial" ? cm / 2.54 : cm) * 10) / 10)); setWeight(String(Math.round((unit === "imperial" ? kg * 2.20462 : kg) * 10) / 10)); update("unit_preference", unit); };
  const removeAccount = async () => { if (!confirm("Delete your profile, workouts, meals, favorites, and uploaded media? This cannot be undone.")) return; try { await api.deleteAccount(); setForm(profileDefaults); setAccount(accountDefaults); setMessage("Account deleted. You can create a fresh profile below."); } catch (e) { setError(errorText(e)); } };
  if (loading) return <Loader label="Loading your profile" />;
  return <><PageHeader title="Your profile" subtitle="Personalize your workout analysis and recovery targets." />{error && <Notice type="error">{error}</Notice>}{message && <Notice type="success">{message}</Notice>}
    <div className="profile-grid"><section className="panel form-panel"><h2>Personal details</h2><div className="avatar-editor">{account.avatar_url ? <img src={api.imageUrl(account.avatar_url) || ""} alt="Profile" /> : <span className="avatar big">{account.display_name.slice(0, 2).toUpperCase()}</span>}<label className="button secondary">Change photo<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={async e => { const file = e.target.files?.[0]; if (file) setAccount(await api.uploadAvatar(file)); }} /></label></div>
      <div className="form-grid"><label>Display name<input value={account.display_name} onChange={e => setAccount({ ...account, display_name: e.target.value })} /></label><label>Email<input type="email" value={account.email || ""} onChange={e => setAccount({ ...account, email: e.target.value || null })} /></label><label>Age<input type="number" min="13" max="100" value={form.age} onChange={e => update("age", Number(e.target.value))} /></label><label>Sex<select value={form.sex} onChange={e => update("sex", e.target.value)}><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option><option value="prefer_not_to_say">Prefer not to say</option></select></label><label>Units<select value={form.unit_preference} onChange={e => switchUnits(e.target.value as "metric" | "imperial")}><option value="metric">Metric (kg, cm)</option><option value="imperial">Imperial (lb, in)</option></select></label><label>Height<div className="input-unit"><input type="number" value={height} onChange={e => setHeight(e.target.value)} /><span>{form.unit_preference === "metric" ? "cm" : "in"}</span></div></label><label>Weight<div className="input-unit"><input type="number" value={weight} onChange={e => setWeight(e.target.value)} /><span>{form.unit_preference === "metric" ? "kg" : "lb"}</span></div></label><label className="wide">Fitness goal<select value={form.fitness_goal} onChange={e => update("fitness_goal", e.target.value)}><option value="maintain_weight">Maintain weight</option><option value="lose_weight">Lose weight</option><option value="gain_muscle">Build muscle</option><option value="endurance_performance">Endurance performance</option></select></label><label className="wide">Maximum prep time (minutes)<input type="number" min="1" max="120" value={form.max_prep_minutes || ""} onChange={e => update("max_prep_minutes", e.target.value ? Number(e.target.value) : null)} /></label><label className="wide">Favorite foods<input value={form.favorite_foods.join(", ")} onChange={e => update("favorite_foods", e.target.value.split(",").map(v => v.trim()).filter(Boolean))} placeholder="Chicken, salmon, Greek yogurt" /></label><label className="wide">Foods to avoid<input value={form.foods_to_avoid.join(", ")} onChange={e => update("foods_to_avoid", e.target.value.split(",").map(v => v.trim()).filter(Boolean))} placeholder="Peanuts, shellfish" /></label></div><div className="form-footer"><button className="button primary" onClick={save}>Save changes</button></div></section>
      <aside className="panel account-panel"><h2>Account</h2><div className="settings-row"><span>◉</span><div><b>Local profile</b><small>Your data stays in this app's database.</small></div></div><div className="settings-row"><span>▣</span><div><b>Privacy</b><small>No sign-in or third-party profile sharing.</small></div></div><hr /><h3>Danger zone</h3><button className="danger-link" onClick={removeAccount}>⌫ Delete account</button><small>This permanently removes all local app data.</small></aside></div>
  </>;
}

function PantryPage() {
  const [items, setItems] = useState<Inventory[]>([]); const [name, setName] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { api.getInventory().then(setItems).catch(e => setError(errorText(e))).finally(() => setLoading(false)); }, []);
  const add = async () => { if (!name.trim()) return; try { const item = await api.addInventory(name); setItems(current => [...current, item]); setName(""); } catch (e) { setError(errorText(e)); } };
  return <><PageHeader title="What I have" subtitle="Add what you have — exact names are not required." action={<span className="ready-pill">✓ Ready</span>} />{error && <Notice type="error">{error}</Notice>}<div className="add-bar"><input value={name} onChange={e => setName(e.target.value)} onKeyDown={e => e.key === "Enter" && add()} placeholder="⌕  e.g. chicken breast, brown rice, apples" /><button className="button primary large" onClick={add}>Add item</button></div><h2>Your items</h2>{loading ? <Loader /> : items.length ? <div className="pantry-grid">{items.map(item => <div className="pantry-item" key={item.id}><span className="food-icon">{item.name.toLowerCase().includes("fruit") || /apple|banana|orange|peach/.test(item.name.toLowerCase()) ? "●" : "♨"}</span><b>{item.name}</b><button aria-label={`Remove ${item.name}`} onClick={async () => { await api.deleteInventory(item.id); setItems(current => current.filter(x => x.id !== item.id)); }}>×</button></div>)}</div> : <Empty title="Your pantry is empty" body="Add a few ingredients to improve meal matches." />}<div className="smart-panel"><span>✣</span><div><h3>Smart matching examples</h3><p>We'll match common names to the right ingredients to make meal planning easier.</p><div><code>chicken → chicken breast</code><code>yogurt → Greek yogurt</code><code>oats → rolled oats</code></div></div></div></>;
}

function UploadPage() {
  const [drag, setDrag] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState("");
  const upload = async (file?: File) => { if (!file) return; try { setUploading(true); setError(""); const workout = await api.uploadWorkout(file); navigate(`/get-meal/review/${workout.id}`); } catch (e) { setError(errorText(e)); setUploading(false); } };
  return <><Stepper step={1} /><PageHeader title="Upload your workout" subtitle="We'll analyze your completed workout and tailor recovery meals to it." />{error && <Notice type="error">{error}</Notice>}<section className={`upload-panel panel ${drag ? "dragging" : ""}`} onDragOver={e => { e.preventDefault(); setDrag(true); }} onDragLeave={() => setDrag(false)} onDrop={e => { e.preventDefault(); setDrag(false); upload(e.dataTransfer.files[0]); }}><span className="upload-icon">⇧</span><h2>{uploading ? "Analyzing your workout…" : "Drop your GPX file here"}</h2><p>or choose a file from your device</p><label className="button primary">{uploading ? "Please wait" : "Choose GPX file"}<input hidden type="file" accept=".gpx,application/gpx+xml" disabled={uploading} onChange={e => upload(e.target.files?.[0])} /></label><small>GPX files up to 10 MB</small></section><div className="flow-benefits"><div><span>1</span><b>Upload securely</b><small>Your GPX is parsed for workout metrics.</small></div><div><span>2</span><b>Review details</b><small>Confirm activity and duration.</small></div><div><span>3</span><b>Get your meal</b><small>Choose from three tailored options.</small></div></div></>;
}

function ReviewPage({ id }: { id: string }) {
  const [workout, setWorkout] = useState<Workout | null>(null); const [activity, setActivity] = useState<Activity>("unknown"); const [duration, setDuration] = useState(""); const [pre, setPre] = useState(""); const [post, setPost] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { api.getWorkout(id).then(w => { setWorkout(w); setActivity(w.activity_type as Activity); setDuration(w.duration_seconds ? String(Math.round(w.duration_seconds / 60)) : ""); }).catch(e => setError(errorText(e))); }, [id]);
  if (!workout && !error) return <Loader label="Loading workout" />;
  const changed = workout && (activity !== workout.activity_type || Math.round(Number(duration) * 60) !== workout.duration_seconds);
  const continueFlow = async () => { if (!workout) return; try { setBusy(true); setError(""); let current = workout; if (changed) { current = await api.correctWorkout(id, activity, Math.round(Number(duration) * 60)); setWorkout(current); } await api.calculateRecovery(id, pre ? Number(pre) : undefined, post ? Number(post) : undefined); navigate(`/get-meal/options/${id}`); } catch (e) { setError(errorText(e)); setBusy(false); } };
  return <><Stepper step={2} /><PageHeader title="Review your workout" subtitle="Make sure these details look right before we calculate your recovery needs." action={<Link className="button secondary" to="/get-meal">Upload another</Link>} />{error && <Notice type="error">{error}</Notice>}{workout && <div className="review-grid"><section className="panel"><div className="workout-hero"><span>◉</span><div><small>Detected activity</small><h2>{friendly(workout.activity_type)}</h2><p>{workout.source_filename}</p></div></div><div className="stats-grid four"><Stat icon="◷" label="Duration" value={`${Math.round((workout.duration_seconds || 0) / 60)} min`} /><Stat icon="⌁" label="Distance" value={workout.distance_meters ? `${(workout.distance_meters / 1000).toFixed(1)} km` : "—"} /><Stat icon="♨" label="Energy" value={workout.estimated_calories ? `${workout.estimated_calories.low}–${workout.estimated_calories.high}` : "—"} /><Stat icon="↗" label="Intensity" value={workout.intensity ? friendly(workout.intensity) : "Needs review"} /></div><hr /><div className="form-grid"><label>Activity<select value={activity} onChange={e => setActivity(e.target.value as Activity)}>{activities.map(item => <option value={item} key={item}>{friendly(item)}</option>)}</select></label><label>Duration (minutes)<input type="number" min="1" value={duration} onChange={e => setDuration(e.target.value)} /></label></div></section><aside className="panel hydration"><span className="water">◉</span><h2>Hydration measurement</h2><p className="muted">Optional: add pre- and post-workout weights for a personalized fluid target.</p><label>Pre-workout weight (kg)<input type="number" value={pre} onChange={e => setPre(e.target.value)} /></label><label>Post-workout weight (kg)<input type="number" value={post} onChange={e => setPost(e.target.value)} /></label><small>Provide both values or leave both empty.</small></aside></div>}<div className="sticky-action"><p>Workout values are estimates for general fitness guidance.</p><button className="button primary large" disabled={busy || activity === "unknown" || !duration || (!!pre !== !!post)} onClick={continueFlow}>{busy ? "Calculating recovery…" : "Calculate recovery & continue →"}</button></div></>;
}

function OptionsPage({ id }: { id: string }) {
  const [recovery, setRecovery] = useState<Recovery | null>(null); const [meals, setMeals] = useState<Meal[]>([]); const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api.getRecovery(id), api.getMeals(id)]).then(([r, m]) => { setRecovery(r); setMeals(m.recommendations); }).catch(e => setError(errorText(e))).finally(() => setLoading(false)); }, [id]);
  const create = async () => { try { setGenerating(true); setError(""); const result = await api.generateMeals(id); const initial = result.recommendations.map(meal => ({ ...meal, image_status: "generating" })); setMeals(initial); setGenerating(false); result.recommendations.forEach(meal => api.generateImage(meal.id).then(updated => setMeals(current => current.map(item => item.id === updated.id ? updated : item))).catch(() => setMeals(current => current.map(item => item.id === meal.id ? { ...item, image_status: "failed" } : item)))); } catch (e) { setError(errorText(e)); setGenerating(false); } };
  const select = async (meal: Meal) => { await api.selectMeal(meal.id); navigate(`/meals/${meal.id}`); };
  const toggleFavorite = async (meal: Meal) => { if (meal.favorite) await api.unfavoriteMeal(meal.id); else await api.favoriteMeal(meal.id); setMeals(current => current.map(item => item.id === meal.id ? { ...item, favorite: !item.favorite } : item)); };
  if (loading) return <Loader label="Preparing meal options" />;
  return <><Stepper step={3} /><PageHeader title="Meal options" subtitle="Meals tailored to your workout and recovery goals." action={<Link className="text-link" to={`/get-meal/review/${id}`}>⚙ Update setup</Link>} />{error && <Notice type="error">{error}</Notice>}{recovery && <div className="targets"><Stat icon="◡" label="Protein target" value={`${recovery.protein_g.low}–${recovery.protein_g.high} g`} /><Stat icon="⌁" label="Carbohydrate target" value={`${recovery.carbs_g.low}–${recovery.carbs_g.high} g`} /><Stat icon="◉" label="Hydration" value={recovery.fluid_ml ? `${recovery.fluid_ml.low}–${recovery.fluid_ml.high} ml` : "Regular fluids"} /></div>}{!meals.length ? <Empty title="Ready for tailored meals" body="Generate three options based on your workout, goals, and pantry." action={<button className="button primary large" disabled={generating} onClick={create}>{generating ? "Generating recommendations…" : "Generate meal options"}</button>} /> : <div className="options-grid">{meals.map((meal, index) => <MealCard key={meal.id} meal={meal} featured={index === 0} onSelect={() => select(meal)} onFavorite={() => toggleFavorite(meal)} />)}</div>}<p className="page-footnote">ⓘ Recommendations update as your progress and preferences evolve.</p></>;
}

function MealDetailPage({ id }: { id: string }) {
  const [meal, setMeal] = useState<Meal | null>(null); const [error, setError] = useState(""); const [selecting, setSelecting] = useState(false);
  useEffect(() => { api.getMeal(id).then(setMeal).catch(e => setError(errorText(e))); }, [id]);
  if (!meal && !error) return <Loader label="Loading recipe" />; if (!meal) return <Empty title="Meal not found" body={error} action={<Link className="button secondary" to="/favorites">View favorites</Link>} />;
  const select = async () => { try { setSelecting(true); setError(""); const result = await api.selectMeal(id); setMeal(current => current ? { ...current, selected: true, selected_at: result.selected_at } : current); } catch (e) { setError(errorText(e)); } finally { setSelecting(false); } };
  const favorite = async () => { if (meal.favorite) await api.unfavoriteMeal(id); else await api.favoriteMeal(id); setMeal({ ...meal, favorite: !meal.favorite }); };
  return <><div className="detail-top"><button className="back-link" onClick={() => history.back()}>‹ Back</button><div><button className="icon-button detail-heart" onClick={favorite}>{meal.favorite ? "♥" : "♡"}</button><button className="button primary large" disabled={selecting || meal.selected} onClick={select}>{selecting ? "Selecting meal…" : meal.selected ? "✓ I'm making this" : "I'm making this"}</button></div></div><PageHeader title={meal.name} />{error && <Notice type="error">{error}</Notice>}{meal.selected && <Notice type="success">✓ Meal selected. You're all set to make it.</Notice>}<div className="detail-hero"><MealPhoto meal={meal} /><aside><Stat icon="◷" label="Total time" value={`${meal.prep_minutes} min`} /><Stat icon="♨" label="Calories" value={`${meal.estimated_calories} kcal`} /><Stat icon="◡" label="Protein" value={`${meal.protein_g} g`} /><Stat icon="⌁" label="Carbohydrates" value={`${meal.carbs_g} g`} /><Stat icon="♧" label="Difficulty" value={meal.prep_minutes <= 15 ? "Easy" : "Moderate"} /></aside></div><div className="recipe-grid"><section className="panel"><h2>▣ Ingredients</h2><p className="muted">1 serving</p><div className="ingredient-list">{meal.ingredients.map((item, index) => <div key={`${item.name}-${index}`}><span>{item.name}</span><b>{item.quantity} {item.unit}</b><small className={item.available ? "available" : "missing"}>{item.available ? "● Available" : "○ Missing"}</small></div>)}</div></section><section className="panel"><h2>♨ Preparation</h2><p className="muted">Step-by-step</p><ol className="steps">{meal.preparation_steps.map(step => <li key={step}>{step}</li>)}</ol><Notice>Tip: Taste and adjust seasoning just before serving.</Notice></section><section className="panel nutrition"><h2>▥ Nutrition</h2><p className="muted">Per serving (est.)</p>{[["Calories", `${meal.estimated_calories} kcal`], ["Protein", `${meal.protein_g} g`], ["Carbohydrates", `${meal.carbs_g} g`], ["Fat", `${meal.fat_g} g`]].map(([key, value]) => <div key={key}><b>{key}</b><span>{value}</span></div>)}<small>Values are estimates and may vary based on ingredients and portion sizes.</small></section></div></>;
}

function FavoritesPage() {
  const [items, setItems] = useState<Favorite[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { api.getFavorites().then(setItems).catch(e => setError(errorText(e))).finally(() => setLoading(false)); }, []);
  return <><PageHeader title="Favorites" subtitle="The recovery meals you want to make again." />{error && <Notice type="error">{error}</Notice>}{loading ? <Loader /> : items.length ? <div className="favorite-grid">{items.map(item => <article className="favorite-card panel" key={item.id}>{item.image_url ? <img src={api.imageUrl(item.image_url) || ""} alt={item.meal.name} /> : <div className="photo-fallback">♨</div>}<div><h2>{item.meal.name}</h2><p>{item.meal.prep_minutes} min · {item.meal.estimated_calories} kcal · {item.meal.protein_g}g protein</p><p className="muted clamp">{item.meal.rationale}</p><div className="card-actions"><Link className="button secondary" to={`/favorites/${item.id}`}>View recipe</Link><button className="button ghost-danger" onClick={async () => { await api.deleteFavorite(item.id); setItems(current => current.filter(x => x.id !== item.id)); }}>Remove</button></div></div></article>)}</div> : <Empty icon="♡" title="No favorites yet" body="Tap the heart on any meal to save it here." action={<Link className="button primary" to="/get-meal">Get a meal</Link>} />}</>;
}

function FavoriteDetailPage({ id }: { id: string }) {
  const [item, setItem] = useState<Favorite | null>(null); const [error, setError] = useState(""); useEffect(() => { api.getFavorite(id).then(setItem).catch(e => setError(errorText(e))); }, [id]); if (!item && !error) return <Loader />; if (!item) return <Empty title="Favorite not found" body={error} />; const meal = item.meal; return <><div className="detail-top"><Link to="/favorites" className="back-link">‹ Back to favorites</Link><button className="button secondary" onClick={async () => { await api.deleteFavorite(id); navigate("/favorites"); }}>Remove favorite</button></div><PageHeader title={meal.name} /><div className="detail-hero favorite-detail">{item.image_url ? <div className="meal-photo"><img src={api.imageUrl(item.image_url) || ""} alt={meal.name} /></div> : <div className="meal-photo photo-fallback">♨</div>}<aside><Stat icon="◷" label="Total time" value={`${meal.prep_minutes} min`} /><Stat icon="♨" label="Calories" value={`${meal.estimated_calories} kcal`} /><Stat icon="◡" label="Protein" value={`${meal.protein_g} g`} /></aside></div><div className="recipe-grid two"><section className="panel"><h2>Ingredients</h2><div className="ingredient-list">{meal.ingredients.map((ingredient, i) => <div key={`${ingredient.name}-${i}`}><span>{ingredient.name}</span><b>{ingredient.quantity} {ingredient.unit}</b></div>)}</div></section><section className="panel"><h2>Preparation</h2><ol className="steps">{meal.preparation_steps.map(step => <li key={step}>{step}</li>)}</ol></section></div></>;
}

function ProgressPage() {
  const now = new Date(); const [month, setMonth] = useState(`${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`); const [data, setData] = useState<Progress | null>(null); const [error, setError] = useState("");
  useEffect(() => { setData(null); api.getProgress(month).then(setData).catch(e => setError(errorText(e))); }, [month]);
  const shift = (delta: number) => { const [year, m] = month.split("-").map(Number); const d = new Date(year, m - 1 + delta, 1); setMonth(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`); };
  const firstOffset = data?.days.length ? new Date(`${data.days[0].date}T12:00:00`).getDay() : 0;
  return <><PageHeader title={new Date(`${month}-15T12:00:00`).toLocaleDateString(undefined, { month: "long", year: "numeric" })} action={<div className="calendar-actions"><button onClick={() => shift(-1)}>‹</button><button onClick={() => setMonth(`${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`)}>Today</button><button onClick={() => shift(1)}>›</button></div>} />{error && <Notice type="error">{error}</Notice>}{!data ? <Loader label="Loading progress" /> : <><div className="calendar-weekdays">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map(day => <b key={day}>{day}</b>)}</div><div className="calendar-grid">{Array.from({ length: firstOffset }, (_, i) => <div className="calendar-day blank" key={`blank-${i}`} />)}{data.days.map(day => <div className={`calendar-day ${day.is_today ? "today" : ""} ${day.is_future ? "future" : ""}`} key={day.date}><div><b>{Number(day.date.slice(-2))}</b><span className={day.meal ? "logged" : ""} /></div>{day.meal?.image_url ? <img src={api.imageUrl(day.meal.image_url) || ""} alt="" /> : <div className="calendar-placeholder">{day.workout ? "◉" : ""}</div>}{day.workout ? <Link to={`/get-meal/review/${day.workout.id}`} className="mini-button">◉ View workout</Link> : <span />}</div>)}</div><div className="calendar-legend"><span><i className="dot green" /> Meal selected</span><span><i className="dot" /> No meal selected</span><span><i className="today-box" /> Today</span><span><b>◉ View workout</b> Open workout</span><strong>◆ {data.streak}-day streak</strong></div></>}</>;
}

function App() {
  const path = usePath(); const parts = path.split("/").filter(Boolean); let page;
  if (path === "/") page = <HomePage />;
  else if (path === "/profile") page = <ProfilePage />;
  else if (path === "/pantry") page = <PantryPage />;
  else if (path === "/favorites") page = <FavoritesPage />;
  else if (parts[0] === "favorites" && parts[1]) page = <FavoriteDetailPage id={parts[1]} />;
  else if (path === "/progress") page = <ProgressPage />;
  else if (path === "/get-meal") page = <UploadPage />;
  else if (parts[0] === "get-meal" && parts[1] === "review" && parts[2]) page = <ReviewPage id={parts[2]} />;
  else if (parts[0] === "get-meal" && parts[1] === "options" && parts[2]) page = <OptionsPage id={parts[2]} />;
  else if (parts[0] === "meals" && parts[1]) page = <MealDetailPage id={parts[1]} />;
  else page = <Empty title="Page not found" body="That page doesn't exist." action={<Link to="/" className="button primary">Go home</Link>} />;
  return <Layout path={path}>{page}</Layout>;
}

export default App;
